### ISSUE TITLE
Files linked in this book do not work.

### ISSUE THREAD

**Issue by RumPyrat** [PacktPublishing/Learn-Ethical-Hacking-from-Scratch#1]
I've tried the Github as well as the Packt website and I can't download the files necessary to follow along with this book.  What am I missing here>?

**Comment by githubce** [comment]
Please click on Clone or Download on this repository or perform the following command in Terminal:
git clone https://github.com/PacktPublishing/Learn-Ethical-Hacking-from-Scratch

If there are any additional files needed other than the ones present in this repository, please reopen the issue and mention it in detail.
